USE [DEMO_PhanQuyen]
GO
/**** object: Table [dbo].[ROLE]**/
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[ROLE](
	[ID][numeric](18,0)not null ,
	[NAME] [nvarchar](50)null,
	CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON[PRIMARY]

GO  


USE[DEMO_PhanQuyen]
GO 

SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO 

CREATE TABLE [dbo].[USER](
	[ID] [numeric](18,0) not null,
	[NAME] [nvarchar](50) not null,
	[PASSWORD][nvarchar](50) not null,
	[STATUS][numeric](18,0) null,
	[CREATE_DATE][date] null,
	[UPDATE_DATE][date]null,
	CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED(
		[ID] ASC 
	)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
)ON [PRIMARY]
GO 

USE[DEMO_PhanQuyen]
GO 


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON 
GO

CREATE TABLE [dbo].[USER_ROLE](
	[ID] [numeric] (18,0) NOT null,
	[USER_ID] [numeric] (18,0) null,
	[ROLE_ID] [numeric](18,0) null,
	CONSTRAINT [PK_USER_ROLE] PRIMARY KEY CLUSTERED(
		[ID] ASC 
	)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON
	) )ON [PRIMARY]
	GO
